[package]
name = "themelio-nodeprot"
version = "0.6.3-alpha.0"
authors = ["Themelio Labs"]
edition = "2018"

description = "High-level API for the Themelio full node peer-to-peer protocol."
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-nodeprot"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serde]
version = "1.0.132"
features = ["derive"]

[dependencies]
cached = "0.26.2"
hex = "0.4.3"
log = "0.4.14"
melnet = "0.1.12"
novasmt = "0.1.10"
smol = "1.2.5"
smolscale = "0.3.16"
stdcode = "0.1.4"
themelio-stf = "0.6.17"
tmelcrypt = "0.2.3"
thiserror = "1.0.30"
