[package]
name = "themelio-nodeprot"
version = "0.5.2-alpha.0"
authors = ["Themelio Labs"]
edition = "2018"

description = "High-level API for the Themelio full node peer-to-peer protocol."
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-nodeprot"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror= "1.0.30"
stdcode= "0.1.4"
themelio-stf= "0.6.11"
tmelcrypt= "0.2.3"
melnet= "0.1.12"
# acidjson= "0.1.0"
serde={ version = "1.0.132", features = ["derive"] }

novasmt= "0.1.10"

cached= "0.26.2"
hex= "0.4.3"

smol= "1.2.5"
log= "0.4.14"
smolscale = "0.3.16"
