[package]
name = "themelio-nodeprot"
version = "0.10.6-alpha.0"
authors = ["Themelio Labs"]
edition = "2018"

description = "High-level API for the Themelio full node peer-to-peer protocol."
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-nodeprot"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serde]
version = "1.0.133"
features = ["derive"]

[dependencies]
# cached = "0.26.2"
hex = "0.4.3"
log = "0.4.14"
melnet = "0.2.0"
novasmt = "0.2.13"
smol = "1.2.5"
smolscale = "0.3.16"
stdcode = "0.1.7"
themelio-stf = "0.9"
themelio-structs= "0.2.0"
tmelcrypt = "0.2.4"
thiserror = "1.0.30" 
anyhow= "1.0.52"
async-trait = "0.1.52"
moka = "0.7.1"
bytes = "1.1.0"
derivative = "2.2.0"

[features]
server=[]
