[package]
name = "themelio-nodeprot"
version = "0.4.1"
authors = ["Themelio Labs"]
edition = "2018"

description = "High-level API for the Themelio full node peer-to-peer protocol."
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-nodeprot"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdcode= "0.1.2"
themelio-stf= "0.5"
tmelcrypt= "0.1.0"
melnet= "0.1.0"
serde={ version = "1.0.126", features = ["derive"] }

novasmt= "0.1.9"

cached= "0.23.0"
hex= "0.4.3"

smol= "1.2.5"
log= "0.4.14"
smolscale = "0.3.11"
