[package]
name = "themelio-nodeprot"
version = "0.9.1-alpha.0"
authors = ["Themelio Labs"]
edition = "2018"

description = "High-level API for the Themelio full node peer-to-peer protocol."
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-nodeprot"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serde]
version = "1.0.133"
features = ["derive"]

[dependencies]
# cached = "0.26.2"
hex = "0.4.3"
log = "0.4.14"
melnet = "0.2"
novasmt = "0.2.6"
smol = "1.2.5"
smolscale = "0.3.16"
stdcode = "0.1.4"
themelio-stf = "0.8"
themelio-structs="0.1.2"
tmelcrypt = "0.2.3"
thiserror = "1.0.30"
anyhow="1"
async-trait = "0.1.52"

[features]
server=[]
